name: Request Universal Login Auth0

on:
  push:
    branches: [master, develop, homolog]


jobs:
  update_universal_login:
    name: Update Universal Login
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: 16

        - name: Set env to develop
          if: endsWith(github.ref, '/develop')
          run: |
            echo "environment_type=develop" >> $GITHUB_ENV

        - name: Set env to homolog
          if: endsWith(github.ref, '/homolog')
          run: |
            echo "environment_type=homolog" >> $GITHUB_ENV

        - name: Set env to production
          if: endsWith(github.ref, '/master')
          run: |
            echo "environment_type=production" >> $GITHUB_ENV

        - name: Print environment_type defined
          run: |
            echo "${{ env.environment_type }}"
            
        - name: Testing actions
          uses: actions/action-testing@v1.2
          with:
            who-to-greet: 'Mona the Octocat'
            
        - name: Get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"
